// <auto-generated />
using System;
using HelloDarlingMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelloDarlingMVC.Migrations
{
    [DbContext(typeof(HelloDarlingContext))]
    partial class HelloDarlingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelloDarlingMVC.Models.Appearance", b =>
                {
                    b.Property<int>("AppearanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HairColor")
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.HasKey("AppearanceId");

                    b.ToTable("Appearance");
                });

            modelBuilder.Entity("HelloDarlingMVC.Models.Interests", b =>
                {
                    b.Property<int>("InterestsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Books")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Cars")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Movies")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Music")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Sports")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TVgame")
                        .HasColumnType("varchar(32)");

                    b.HasKey("InterestsId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("HelloDarlingMVC.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Favorite")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchingUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("HelloDarlingMVC.Models.Preference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("HelloDarlingMVC.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.Property<string>("IdentityNO")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.Property<int?>("UserAppearanceAppearanceId")
                        .HasColumnType("int");

                    b.Property<int?>("UserInterestsInterestsId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPreferencePreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("UsersCategory")
                        .HasColumnType("int")
                        .HasMaxLength(5);

                    b.HasKey("UserId");

                    b.HasIndex("UserAppearanceAppearanceId");

                    b.HasIndex("UserInterestsInterestsId");

                    b.HasIndex("UserPreferencePreferenceId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HelloDarlingMVC.Models.Match", b =>
                {
                    b.HasOne("HelloDarlingMVC.Models.User", null)
                        .WithMany("Matches")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("HelloDarlingMVC.Models.User", b =>
                {
                    b.HasOne("HelloDarlingMVC.Models.Appearance", "UserAppearance")
                        .WithMany()
                        .HasForeignKey("UserAppearanceAppearanceId");

                    b.HasOne("HelloDarlingMVC.Models.Interests", "UserInterests")
                        .WithMany()
                        .HasForeignKey("UserInterestsInterestsId");

                    b.HasOne("HelloDarlingMVC.Models.Preference", "UserPreference")
                        .WithMany()
                        .HasForeignKey("UserPreferencePreferenceId");

                    b.OwnsMany("HelloDarlingMVC.Models.Messages", "UserMessages", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("MessagesId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("JoinDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("MessageStatus")
                                .HasColumnType("int");

                            b1.HasKey("UserId", "MessagesId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
